### PR TITLE
Delegate package installation to rstantools

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates your package's installation/compilation of Stan models to be better handled by `rstantools` for compatibility with future releases of `rstan`

### CODE REVIEW

**Comment by kkmann** [comment]
Hey @andrjohns thank for your PR! Could you help me understand the background for the proposed change a bit more? I must admit that I am not an rstan integration expert (yet) though. If I see this correctly, you added rstantools back in as dependency. I intentially removed it (it is a development dependency only required when we update the stan model) and I would like to keep it that way unless there is an important reason to do otherwise. Is there a way of keeping it this way with the changes that you are making upstream or is this patter unsupported going forward?

**Comment by andrjohns** [comment]
Sure! The issue is that your current structure means that your package will only be compatible with the versions of `rstan` and `StanHeaders` that were installed when your model code (the `src` folder) was generated. 

As `rstan`/`StanHeaders` is updated, there are changes to the c++ that gets generated from a given stan model and changes to the compilation/linker flags that are used to compile this. By using `rstantools` with the `configure` scripts, the c++ and the needed `Makevars` are re-generated at installation. This means that your package will always be compatible with changes/updates to `rstan` and `StanHeaders`

**Comment by kkmann** [comment]
coverage is an issue with the pipeline setup, can be ignored for now, see https://github.com/5monkeys/cobertura-action/issues/80#issue-1582133106

**Comment by kkmann** [comment]
> Sure! The issue is that your current structure means that your package will only be compatible with the versions of `rstan` and `StanHeaders` that were installed when your model code (the `src` folder) was generated.
> 
> As `rstan`/`StanHeaders` is updated, there are changes to the c++ that gets generated from a given stan model and changes to the compilation/linker flags that are used to compile this. By using `rstantools` with the `configure` scripts, the c++ and the needed `Makevars` are re-generated at installation. This means that your package will always be compatible with changes/updates to `rstan` and `StanHeaders`

I guess this means I would run into issues down the line that are hard to debug unless you are a stan/C++ expert. Accepting rstantools as dependency seem to be the right trade-off then. Thanks for clarifying and fixing this in one go!

**Review by kkmann — APPROVED** [review]
thanks again!

**Pull request merged**
